apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.k8s.app_name }}-svc
  labels:
    app: {{ .Values.k8s.app_name }}
    app.kubernetes.io/name: {{ .Values.k8s.app_name }}
    app.kubernetes.io/instance: {{ .Values.k8s.app_name }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.k8s.app_name }}
  ports:
    - port: {{ .Values.k8s.app_port }}
      targetPort: {{ .Values.k8s.app_targetPort }}
      protocol: TCP
